### ISSUE TITLE
Unhandled Exception with 3ds game

### ISSUE THREAD

**Issue by jakerman777** [MeltyPlayer/FinModelUtility#6]
Hi, I'm trying to extract models from the Yugioh saikyo card battle game but I'm getting the error that I haven't installed hackingtoolkit9ds. I've installed several times, ran hackingtoolkit9ds on its own and it doesn't throw any folders. I tried another version and it worked, but it doesn't work with FinmodelUtility, it just stays running and doesn't do anything (it's been like this for an hour)

**Comment by MeltyPlayer** [comment]
Sorry, I haven't added support for that game yet so it won't work yet even if you install hackingtoolkit9ds. Only the games that are listed in the README will work, due to the limited number of supported formats.
